version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    entrypoint: python
    volumes:
      - ./src:/app
    depends_on:
      - mysql
    networks:
      - scrapper

  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "3323:3306"
    environment:
      MYSQL_DATABASE: scrapper
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: root
    networks:
      - scrapper

networks:
  scrapper:
    driver: bridge
    external: true